# Generated by Django 3.2 on 2021-05-08 06:19

from django.db import migrations

import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210507_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
